//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by Mighty.rc
//
#define IDP_SOCKETS_INIT_FAILED         100
#define IDR_MAINFRAME                   101
#define IDR_MIGHTYTYPE                  102
#define IDW_BEGIN                       300
#define IDW_NOTIFY                      301
#define IDW_SCORE                       302
#define IDW_MIGHTY                      303
#define IDW_SUFFLE                      304
#define IDW_SUFFLE2                     305
#define IDW_WIN                         306
#define IDW_JOKER                       307
#define IDW_JOKERCALL                   308
#define IDW_KILLDEDJOKER                309
#define IDW_KILLEDJOKER                 310
#define IDW_KIRUDA                      311
#define IDW_CARD                        312
#define IDW_GETCARD                     313
#define IDW_GETCARD2                    314
#define IDW_LOSE                        315
#define IDW_BEEP                        316
#define IDW_GOAL                        317
#define IDW_CHULK                       318
#define IDW_GIVEUP                      319
#define IDW_CARDSETUP                   320
#define IDW_CARDSET                     321
#define IDC_FOCUS                       500
#define IDI_IEX                         600
#define IDI_MYCOM                       601
#define IDB_NOTHING                     700
#define IDB_SPADE                       701
#define IDB_DIAMOND                     702
#define IDB_HEART                       703
#define IDB_CLOVER                      704
#define IDB_STOP                        705
#define IDB_SA                          710
#define IDB_S2                          711
#define IDB_S3                          712
#define IDB_S4                          713
#define IDB_S5                          714
#define IDB_S6                          715
#define IDB_S7                          716
#define IDB_S8                          717
#define IDB_S9                          718
#define IDB_S10                         719
#define IDB_SJ                          720
#define IDB_SQ                          721
#define IDB_SK                          722
#define IDB_DA                          723
#define IDB_D2                          724
#define IDB_D3                          725
#define IDB_D4                          726
#define IDB_D5                          727
#define IDB_D6                          728
#define IDB_D7                          729
#define IDB_D8                          730
#define IDB_D9                          731
#define IDB_D10                         732
#define IDB_DJ                          733
#define IDB_DQ                          734
#define IDB_DK                          735
#define IDB_HA                          736
#define IDB_H2                          737
#define IDB_H3                          738
#define IDB_H4                          739
#define IDB_H5                          740
#define IDB_H6                          741
#define IDB_H7                          742
#define IDB_H8                          743
#define IDB_H9                          744
#define IDB_H10                         745
#define IDB_HJ                          746
#define IDB_HQ                          747
#define IDB_HK                          748
#define IDB_CA                          749
#define IDB_C2                          750
#define IDB_C3                          751
#define IDB_C4                          752
#define IDB_C5                          753
#define IDB_C6                          754
#define IDB_C7                          755
#define IDB_C8                          756
#define IDB_C9                          757
#define IDB_C10                         758
#define IDB_CJ                          759
#define IDB_CQ                          760
#define IDB_CK                          761
#define IDB_JOKER                       762
#define IDB_MASK                        763
#define IDB_BACK1                       770
#define IDB_BACK2                       771
#define IDB_BACK3                       772
#define IDB_BACK4                       773
#define IDB_BACK5                       774
#define IDB_BACK6                       775
#define IDB_BACK7                       776
#define IDB_BACK8                       777
#define IDB_BACK9                       778
#define IDB_BACK10                      779
#define IDB_BACK11                      780
#define IDB_GRAY                        781
#define IDB_MIGHTY                      782
#define IDB_PERSON                      783
#define IDB_SHADE                       784
#define IDD_ABOUTBOX                    800
#define IDD_OPTION_GENERAL              801
#define IDD_OPTION_PAGE                 802
#define IDD_RULE_PAGE                   803
#define IDD_RULE_CARD                   804
#define IDD_OPTION_BOSSKEY              805
#define IDD_OPTION_CARD                 806
#define IDD_SELECTBACK                  807
#define IDD_OPTION_BACKGROUND           808
#define IDD_OPTION_DSB                  809
#define IDD_OPTION_SPEED                810
#define IDD_OPTION_RULE                 811
#define IDD_OPTION_AI                   812
#define IDD_MAIINFO                     813
#define IDD_OPTION_COMM                 814
#define IDD_RULE_GENERAL                815
#define IDD_RULE_ELECTION               816
#define IDD_RULE_CONSTRAIN              817
#define IDD_RULE_DEALMISS               818
#define IDD_RULE_SCORE                  819
#define IDD_RULE_SPECIAL                820
#define IDD_SCOREBOARD                  821
#define IDD_LOG                         822
#define IDC_CLOCKWISE                   1001
#define IDC_USESOUND                    1002
#define IDC_USETERM                     1003
#define IDC_SORTMODE                    1004
#define IDC_SORTMODE1                   1005
#define IDC_SORTMODE2                   1006
#define IDC_SORTMODE3                   1007
#define IDC_SORTMODE4                   1008
#define IDC_BOSSTYPE                    1009
#define IDC_BOSSTYPE1                   1010
#define IDC_BOSSTYPE2                   1011
#define IDC_BOSSTYPE3                   1012
#define IDC_BOSSTYPE4                   1013
#define IDC_BACKSELECT                  1014
#define IDC_SAMPLEBACK                  1015
#define IDC_ZOOMCARD                    1016
#define IDC_CARDHELP                    1017
#define IDC_BACKBROWSE                  1018
#define IDC_CARDTIP                     1019
#define IDC_BACKPIC1                    1020
#define IDC_BACKPIC2                    1021
#define IDC_BACKPIC3                    1022
#define IDC_BACKPIC4                    1023
#define IDC_BACKPIC5                    1024
#define IDC_BACKPIC6                    1025
#define IDC_BACKPIC7                    1026
#define IDC_BACKPIC8                    1027
#define IDC_BACKPIC9                    1028
#define IDC_BACKPIC10                   1029
#define IDC_BACKPIC11                   1030
#define IDC_SAMPLEBACKGROUND            1031
#define IDC_DEFCOLSELECT                1032
#define IDC_ATTCOLSELECT                1033
#define IDC_BACKGROUNDCOLSELECT         1034
#define IDC_USEBACKGROUND               1035
#define IDC_BACKALIGN                   1036
#define IDC_BACKALIGN1                  1037
#define IDC_BACKALIGN2                  1038
#define IDC_BACKGROUNDBROWSE            1039
#define IDC_DSBOPAQUE                   1040
#define IDC_DSBTEXTCOLSELECT            1041
#define IDC_DSBSTRONG1COLSELECT         1042
#define IDC_DSBSTRONG2COLSELECT         1043
#define IDC_DSBGRAYCOLSELECT            1044
#define IDC_DSBSAMPLE                   1045
#define IDC_DSBSHADEMODE                1046
#define IDC_DSBSHADEMODE1               1047
#define IDC_DSBSHADEMODE2               1048
#define IDC_CARDSPEED                   1049
#define IDC_CARDMOTION                  1050
#define IDC_DELAYONECARD                1051
#define IDC_DELAYONETURN                1052
#define IDC_SHOWDEALING                 1053
#define IDC_RULEPRESET                  1054
#define IDC_RULESTRING                  1055
#define IDC_SHOWRULE                    1056
#define IDC_PLAYERNAME0                 1057
#define IDC_PLAYERNAME1                 1058
#define IDC_PLAYERNAME2                 1059
#define IDC_PLAYERNAME3                 1060
#define IDC_PLAYERNAME4                 1061
#define IDC_PLAYERNAME5                 1062
#define IDC_AIBROWSE0                   1063
#define IDC_AIBROWSE1                   1064
#define IDC_AIBROWSE2                   1065
#define IDC_AIBROWSE3                   1066
#define IDC_AIBROWSE4                   1067
#define IDC_AIBROWSE5                   1068
#define IDC_AISETTING0                  1069
#define IDC_AISETTING1                  1070
#define IDC_AISETTING2                  1071
#define IDC_AISETTING3                  1072
#define IDC_AISETTING4                  1073
#define IDC_AISETTING5                  1074
#define IDC_AIPATH0                     1075
#define IDC_AIPATH1                     1076
#define IDC_AIPATH2                     1077
#define IDC_AIPATH3                     1078
#define IDC_AIPATH4                     1079
#define IDC_AIPATH5                     1080
#define IDC_MAIINFO_NAME                1081
#define IDC_MAIINFO_MAJOR               1082
#define IDC_MAIINFO_MINOR               1083
#define IDC_MAIINFO_EXPLAIN             1084
#define IDC_MAIINFO_FILENAME            1085
#define IDC_RESETPATH                   1086
#define IDC_CHANGEOPTION                1087
#define IDC_OBSERVER                    1088
#define IDC_PORT                        1089
#define IDC_CHATDSBTIMEOUT              1090
#define IDC_ADDRESS                     1091
#define IDC_RESETSCORE                  1092
#define IDC_DETAILSCORE                 1093
#define IDC_2MA                         1094
#define IDC_3MA                         1095
#define IDC_4MA                         1096
#define IDC_5MA                         1097
#define IDC_6MA                         1098
#define IDC_7MA                         1099
#define IDC_FRIEND                      1100
#define IDC_JOKERFRIEND                 1101
#define IDC_SHOWFRIEND                  1102
#define IDC_FRIENDGETSBEGINER           1103
#define IDC_ATTSCORETHROWNPOINTS        1104
#define IDC_HIDESCORE                   1105
#define IDC_QUOTE                       1106
#define IDC_MINSCORE                    1107
#define IDC_NOKIRUDAADVANTAGE           1108
#define IDC_HIGHSCORE                   1109
#define IDC_BEGINERPASS                 1110
#define IDC_RAISE2FORKIRUDACHANGE       1111
#define IDC_RAISE1FORNOKIRUDACHANGE     1112
#define IDC_NK                          1113
#define IDC_NK1                         1114
#define IDC_NK2                         1115
#define IDC_PASSAGAIN                   1116
#define IDC_INITMIGHTY                  1117
#define IDC_INITMIGHTYEFFECT            1118
#define IDC_LASTMIGHTY                  1119
#define IDC_LASTMIGHTYEFFECT            1120
#define IDC_OVERRIDEMIGHTY              1121
#define IDC_INITJOKER                   1122
#define IDC_INITJOKEREFFECT             1123
#define IDC_LASTJOKER                   1124
#define IDC_LASTJOKEREFFECT             1125
#define IDC_INITKIRUDA                  1126
#define IDC_INITBEGINKIRUDA             1127
#define IDC_INITJOKERCALLEFFECT         1128
#define IDC_JOKERCALLJOKEREFFECT        1129
#define IDC_DM_NOPOINT                  1130
#define IDC_DM_NUM                      1131
#define IDC_DM_ALLPOINT                 1132
#define IDC_DM_MIGHTYISPOINT            1133
#define IDC_DM_JOKERISPOINT             1134
#define IDC_DM_JOKERISREVERSEPOINT      1135
#define IDC_DM_ONLY10                   1136
#define IDC_DM_ONEEYEDJACK              1137
#define IDC_DM_ONLYMIGHTY               1138
#define IDC_DM_ONLYONE                  1139
#define IDC_DM_DUPLICATE                1140
#define IDC_S_0                         1141
#define IDC_S_1                         1142
#define IDC_S_2                         1143
#define IDC_S_3                         1144
#define IDC_S_4                         1145
#define IDC_S_5                         1146
#define IDC_S_6                         1147
#define IDC_S_7                         1148
#define IDC_SS_0                        1149
#define IDC_SS_1                        1150
#define IDC_RUN                         1151
#define IDC_RUN1                        1152
#define IDC_RUN2                        1153
#define IDC_RUN3                        1154
#define IDC_S_REVERSERUN                1155
#define IDC_S_NOFRIEND                  1156
#define IDC_S_NOKIRUDA                  1157
#define IDC_REVERSERUN                  1158
#define IDC_REVERSERUN1                 1159
#define IDC_REVERSERUN2                 1160
#define IDC_CARD_MIGHTY                 1161
#define IDC_CARD_ALTMIGHTY              1162
#define IDC_CARD_JOKERCALL              1163
#define IDC_CARD_ALTJOKERCALL           1164
#define IDC_HUMANNAME                   1165
#define IDC_SB_0                        1166
#define IDC_SB_1                        1167
#define IDC_SB_2                        1168
#define IDC_SB_3                        1169
#define IDC_SB_4                        1170
#define IDC_SB_5                        1171
#define IDC_SB_6                        1172
#define IDC_SB_TAB                      1173
#define IDC_SLOWMACHINE                 1174
#define IDC_SCORE1                      1175
#define IDC_SCORE2                      1176
#define IDC_SCORE3                      1177
#define IDC_SCORE4                      1178
#define IDC_SCORE5                      1179
#define IDC_SCORE6                      1180
#define IDC_CARDSPEEDGROUP              1181
#define IDC_CARDMOTIONGROUP             1182
#define IDC_MONEYASSUPPORT              1183
#define IDC_LOG                         1184
#define IDC_COPYRIGHT                   1185
#define IDC_COPYRIGHT2                  1185
#define IDC_ADDRULE                     1186
#define IDC_REMOVERULE                  1187
#define IDC_BUTTON2                     1188
#define IDD_SETTING                     10000
#define IDC_FACTOR                      10000
#define IDC_USESIMULATION               10001
#define IDD_DETAILSCORE                 10001
#define IDC_GOALMODE                    10002
#define ID_GAME_EXIT                    32771
#define ID_APP_OPTION                   32772
#define ID_APP_SCOREBOARD               32773
#define ID_Menu                         32774
#define ID_LOG_DIALOG                   32775

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        2001
#define _APS_NEXT_COMMAND_VALUE         32780
#define _APS_NEXT_CONTROL_VALUE         1188
#define _APS_NEXT_SYMED_VALUE           2000
#endif
#endif
